### ISSUE TITLE
Deploy workflow fails: lack of secrets

### ISSUE THREAD

**Issue by glennj** [exercism/jq-test-runner#4]
https://github.com/exercism/jq-test-runner/actions/runs/3003990796

@ErikSchierboom upon your return, please have a look.

**Comment by iHiD** [comment]
I've added the secrets. This needs a PR to the terraform repo in the same vein as https://github.com/exercism/terraform/pull/76 - I can merge/deploy that later this week.

The one thing I can't do (through ignorance) is push to Dockerhub, which isn't required for production, but is for local testing and may be for the github action to complete successfully. But if we comment that bit out, I can do the rest. 

FYI, I'm also off next week, so if you want anything doing for this this week, I'm happy to help, but won't be able to next week 🙂 

Thanks for your continued work on it!

**Comment by glennj** [comment]
If the test-runner is blocked, no big deal. There's lots to do on the jq track.

**Comment by ErikSchierboom** [comment]
@glennj @iHiD I've done the Docker hub part and created the terraform PR: https://github.com/exercism/terraform/pull/80
I'll let @iHiD review/merge that PR and then run terraform and provide access to the secrets. Once that is all done, the deploy should work.

**Comment by iHiD** [comment]
Urgh, sorry. I need to get terraform synced after the shambles of the SSL certificate expiring. I'll fix that this week. Feel free to nag me daily @glennj - it'll help keep it at the top of priority list!!

**Comment by glennj** [comment]
Should now be resolved:
https://github.com/exercism/jq-test-runner/actions/runs/3184435493/jobs/5402288769
